name: Python Lint

on:
  push:
    paths:
      - '**.py'
      - 'requirements.txt'
      - 'setup.py'
      - 'pyproject.toml'

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 black isort
        
    - name: Run Black
      run: black . --check
        
    - name: Run Flake8
      run: flake8 .
        
    - name: Run isort
      run: isort . --check-only --diff